"""CI autopilot logic: submission writing, config hashing, failure classification, margins.

Extracted from cli.py for Phase 3 refactoring. Used by run-ci-case and related workflows.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from datetime import datetime as _dt
from pathlib import Path
from typing import Any, Dict

import typer

from .cli_helpers import _write_json
from .path_utils import dump_yaml

from ._optional_imports import require_reactor_scale_compute

_compute_reactor_scale_metrics = require_reactor_scale_compute()
from .submission_packaging import _extract_surface_name
from .version_utils import _get_version_info


def _write_autopilot_submission(
    *,
    case_id: str,
    results_dict: dict,
    case_cfg,
    case_config_dict: dict,
    walltime: float,
    repo_root: Path,
    submissions_dir: Path | None = None,
    case_output_dir: Path | None = None,
) -> None:
    """Create a ``submissions/`` entry so autopilot results appear on the leaderboard.

    The entry is formatted identically to human submissions so that no extra
    columns appear.  Directory structure:
    ``submissions/<surface>/auto/<case_id>/results.json``
    """
    submissions_dir = submissions_dir or (repo_root / "submissions")

    surface_name = _extract_surface_name(
        case_cfg if case_cfg is not None else case_config_dict
    )

    # --- build metrics that match the human-submission format ---
    # Strip fields that human submissions don't have so no extra columns
    # appear on the leaderboard.
    _STRIP_KEYS = {"iterations_used", "walltime_sec", "output_directory"}
    full_metrics = {k: v for k, v in results_dict.items() if k not in _STRIP_KEYS}

    version_info = _get_version_info()
    reactor_scale_metrics = _compute_reactor_scale_metrics(full_metrics, case_cfg)

    iterations_used = int(results_dict.get("iterations_used", 0))
    walltime_sec = float(results_dict.get("walltime_sec", walltime))

    submission = {
        "metadata": {
            "contact": "auto",
            "hardware": "CPU: self-hosted runner",
            "run_date": _dt.now().isoformat(),
            "iterations_used": iterations_used,
            "walltime_sec": walltime_sec,
        },
        "version_info": version_info,
        "metrics": full_metrics,
        "reactor_scale_metrics": reactor_scale_metrics,
    }

    sub_dir = submissions_dir / surface_name / "auto" / case_id
    sub_dir.mkdir(parents=True, exist_ok=True)
    sub_path = sub_dir / "results.json"
    _write_json(sub_path, submission)

    # Write case.yaml so the leaderboard can extract N (ncoils) and n (order)
    case_yaml_path = sub_dir / "case.yaml"
    dump_yaml(case_config_dict, path=case_yaml_path)

    # Copy plot files so leaderboard links (i, f, PP) work.
    # Only Poincaré + B·n plots are generated by CI runs (VMEC/SIMPLE are off).
    if case_output_dir and case_output_dir.is_dir():
        # For Fourier continuation cases, plots live in order_X/ subdirectories.
        # Check the highest-order directory first, then fall back to the top level.
        fc_cfg = case_config_dict.get("fourier_continuation", {})
        search_dirs = [case_output_dir]
        if fc_cfg and fc_cfg.get("enabled", False):
            orders = fc_cfg.get("orders", [])
            if orders:
                highest = max(orders)
                fc_dir = case_output_dir / f"order_{highest}"
                if fc_dir.is_dir():
                    search_dirs.insert(0, fc_dir)
                # Also copy each order_X/ subdirectory into the submission
                for order in sorted(orders):
                    src_order_dir = case_output_dir / f"order_{order}"
                    dst_order_dir = sub_dir / f"order_{order}"
                    if src_order_dir.is_dir():
                        dst_order_dir.mkdir(parents=True, exist_ok=True)
                        for f in src_order_dir.iterdir():
                            if f.is_file():
                                shutil.copy2(f, dst_order_dir / f.name)

        for plot_name in (
            "bn_error_3d_plot.png",
            "bn_error_3d_plot_initial.png",
            "poincare_plot.png",
        ):
            for search_dir in search_dirs:
                # Prefer PNG, fall back to PDF for B·n plots (backward compat)
                exts = (".png", ".pdf") if "bn_error" in plot_name else (".png",)
                for ext in exts:
                    src_name = plot_name.replace(".png", ext) if ext != ".png" else plot_name
                    src = search_dir / src_name
                    if src.exists():
                        shutil.copy2(src, sub_dir / src_name)
                        break
                else:
                    continue
                break

    typer.echo(f"Wrote submission to {sub_path}")


def _config_hash(cfg: Dict[str, Any]) -> str:
    """Deterministic hash of case_config for KB dedup and novelty checking."""
    canonical = json.dumps(cfg, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()[:16]


def _canonical_failure_class(exc: BaseException) -> str:
    """Map raw exception to canonical failure_class for KB queryability."""
    name = type(exc).__name__
    msg = str(exc).lower()
    if "timeout" in msg or "timed out" in msg or name == "TimeoutError":
        return "timeout"
    if "nan" in msg or "inf" in msg or name in ("ValueError", "FloatingPointError"):
        return "nan_in_objective"
    if "vmec" in msg or "VMEC" in name:
        return "vmec_nonconverged"
    if "line search" in msg or "linesearch" in msg or "trust region" in msg:
        return "line_search_fail"
    if "sep" in msg or "separation" in msg or "min_sep" in msg:
        return "min_sep_violation"
    if "validation" in msg:
        return "validation"
    return "unknown"


def _compute_margins(metrics: Dict[str, Any]) -> Dict[str, Any]:
    r"""Compute constraint margins from metrics vs thresholds.

    For "value ≤ threshold" constraints (e.g. curvature, flux):
    :math:`m = \mathtt{threshold} - \mathtt{value}`.
    For "value ≥ threshold" constraints (e.g. coil-coil separation):
    :math:`m = \mathtt{value} - \mathtt{threshold}`.
    Positive margin = constraint satisfied.
    """
    margins: dict = {}
    # cc: separation >= threshold → margin = actual - threshold
    if "final_min_cc_separation" in metrics and "cc_threshold" in metrics:
        margins["cc"] = float(metrics["final_min_cc_separation"]) - float(
            metrics["cc_threshold"]
        )
    if "final_min_cs_separation" in metrics and "cs_threshold" in metrics:
        margins["cs"] = float(metrics["final_min_cs_separation"]) - float(
            metrics["cs_threshold"]
        )
    # msc, curvature, flux, force, torque: value <= threshold → margin = threshold - value
    if "final_mean_squared_curvature" in metrics and "msc_threshold" in metrics:
        margins["msc"] = float(metrics["msc_threshold"]) - float(
            metrics["final_mean_squared_curvature"]
        )
    if "final_max_curvature" in metrics and "curvature_threshold" in metrics:
        margins["curvature"] = float(metrics["curvature_threshold"]) - float(
            metrics["final_max_curvature"]
        )
    if "final_squared_flux" in metrics and "flux_threshold" in metrics:
        margins["flux"] = float(metrics["flux_threshold"]) - float(
            metrics["final_squared_flux"]
        )
    if "final_max_max_coil_force" in metrics and "force_threshold" in metrics:
        margins["force"] = float(metrics["force_threshold"]) - float(
            metrics["final_max_max_coil_force"]
        )
    if "final_max_max_coil_torque" in metrics and "torque_threshold" in metrics:
        margins["torque"] = float(metrics["torque_threshold"]) - float(
            metrics["final_max_max_coil_torque"]
        )
    if "final_max_torsion" in metrics and "torsion_threshold" in metrics:
        margins["torsion"] = float(metrics["torsion_threshold"]) - float(
            metrics["final_max_torsion"]
        )
    return margins


def _write_ci_summary(
    path: Path,
    *,
    case_id: str,
    success: bool,
    failure_reason: str = "",
    failure_class: str = "",
    case_config: dict | None = None,
    metrics: dict | None = None,
    total_score: float = float("inf"),
    iterations_used: int = 0,
    walltime_sec: float = 0.0,
    config_hash: str | None = None,
    margins: dict | None = None,
    random_seed: int | None = None,
    tags: list[str] | None = None,
    parent_ids: list[str] | None = None,
    proposer_mode: str | None = None,
    timing: dict | None = None,
    llm_reasoning: str | None = None,
) -> None:
    """Write a CI summary JSON file (success or failure).

    Parameters
    ----------
    path : Path
        Destination file path (e.g. ``cases/done/<id>/summary.json``).
    case_id : str
        Unique identifier for the CI case.
    success : bool
        Whether the optimisation succeeded.
    failure_reason : str
        Human-readable failure reason (empty on success).
    failure_class : str
        Canonical failure class for KB queryability.
    case_config : dict | None
        Original case configuration dictionary.
    metrics : dict | None
        Numeric optimisation metrics.
    total_score : float
        Primary score (``final_squared_flux``).
    iterations_used : int
        Number of optimiser iterations consumed.
    walltime_sec : float
        Wall-clock time for the run in seconds.
    config_hash : str | None
        Deterministic hash of the case config; computed if not given.
    margins : dict | None
        Constraint margins; computed from *metrics* if not given.
    random_seed : int | None
        Random seed used for the run.
    tags : list[str] | None
        Tags from the CI case JSON.
    parent_ids : list[str] | None
        Parent case IDs from the CI case JSON.
    proposer_mode : str | None
        Proposer that generated this case (``"ga"`` or ``"llm"``).
    timing : dict | None
        Timing breakdown dict from the optimisation results.
    llm_reasoning : str | None
        LLM's explanation for proposing this case (when proposer_mode is ``"llm"``).
    """
    cfg = case_config or {}
    m = metrics or {}
    summary: Dict[str, Any] = {
        "case_id": case_id,
        "random_seed": random_seed,
        "tags": tags if tags is not None else [],
        "parent_ids": parent_ids if parent_ids is not None else [],
        "proposer_mode": proposer_mode,
        "llm_reasoning": llm_reasoning,
        "success": success,
        "total_score": total_score,
        "iterations_used": iterations_used,
        "walltime_sec": walltime_sec,
        "failure_reason": failure_reason,
        "failure_class": failure_class,
        "config_hash": config_hash or _config_hash(cfg),
        "margins": margins if margins is not None else _compute_margins(m),
        "metrics": m,
        "case_config": cfg,
    }
    if timing is not None:
        summary["timing"] = timing
    path.parent.mkdir(parents=True, exist_ok=True)
    _write_json(path, summary)


def _append_failure_to_autopilot_failures(
    failures_path: Path,
    summary_dict: Dict[str, Any],
    *,
    max_entries: int = 500,
) -> None:
    """Append a failed run summary to the autopilot failures JSON file.

    The file format is: ``{"failures": [{...}, ...]}``. Each entry is a
    summary-like dict with case_id, success=False, failure_class, failure_reason,
    config_hash, case_config, tags, parent_ids, etc. The list is trimmed to
    the last *max_entries* to bound file size.

    Parameters
    ----------
    failures_path : Path
        Path to policy/autopilot_failures.json (typically repo_root / "policy"
        / "autopilot_failures.json").
    summary_dict : dict
        Summary dict from _write_ci_summary (must have success=False).
    max_entries : int, optional
        Maximum number of failure entries to retain (default 500).
    """
    failures_path = Path(failures_path)
    failures_path.parent.mkdir(parents=True, exist_ok=True)

    existing: Dict[str, Any] = {"failures": []}
    if failures_path.exists():
        try:
            data = json.loads(failures_path.read_text())
            if isinstance(data, list):
                existing["failures"] = data
            elif isinstance(data, dict) and isinstance(data.get("failures"), list):
                existing["failures"] = data["failures"]
        except (json.JSONDecodeError, OSError):
            pass

    # Ensure we only append failures
    entry = dict(summary_dict)
    entry["success"] = False
    existing["failures"].append(entry)
    existing["failures"] = existing["failures"][-max_entries:]
    _write_json(failures_path, existing)
